### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by xfce** [remrc/Self-Balancing-Bike#1]
Hi,
  From the readme, said bellow
First connect to controller over bluetooth. You will see a message that you need to calibrate the balancing point. Send c+ from serial monitor. This activate calibrating procedure. Set the bike to balancing point. Hold still when the bike does not fall to either side. Send c- from serial monitor. This will write the offsets to the EEPROM. After calibrating, the bike will begin to balance.
   Does this mean just upload the firmware, fellow above steps, no need to change the code twice, upload tirmware twice as you said in thingiverse

Uncomment first line, and comment second line.

Tuning();
//readControlParameters();

Send c+ for calibrating balancing point.
After calibrating do as it was.

//Tuning();
readControlParameters();

Control only works when the bike is balancing...

Thanks

**Comment by remrc** [comment]
Of course, after calibrating comment first line and uncomment second.

//Tuning();
readControlParameters();

and upload code.

without this the bike will balance but not be controlled from the phone.

**Comment by xfce** [comment]
@remrc Thanks I will try
